routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::group(['prefix' => 'admin'], function () {

	Route::name('admin.index')->get('/', 'DashboardController@index');

	Route::group(['prefix' => 'datatables'], function () {
		Route::name('admin.datatables.categories')->get('categories', 'DatatablesController@categories');
		Route::name('admin.datatables.modules')->get('modules', 'DatatablesController@modules');
		Route::name('admin.datatables.products')->get('products', 'DatatablesController@products');
	    Route::name('admin.datatables.users')->get('users', 'DatatablesController@users');
	});

	Route::group(['prefix' => 'categories'], function () {
	    Route::name('admin.categories.index')->get('/', 'CategoriesController@index');
	    Route::name('admin.categories.create')->get('/create', 'CategoriesController@create');
	    Route::name('admin.categories.store')->post('/', 'CategoriesController@store');
	    Route::name('admin.categories.show')->get('/{category}', 'CategoriesController@show');
	    Route::name('admin.categories.edit')->get('/{category}/edit', 'CategoriesController@edit');
	    Route::name('admin.categories.update')->put('/{category}', 'CategoriesController@update');
	    Route::name('admin.categories.destroy')->delete('/{category}', 'CategoriesController@destroy');
	});

	Route::group(['prefix' => 'products'], function () {
	    Route::name('admin.products.index')->get('/', 'ProductsController@index');
	    Route::name('admin.products.create')->get('/create', 'ProductsController@create');
	    Route::name('admin.products.store')->post('/', 'ProductsController@store');
	    Route::name('admin.products.show')->get('/{product}', 'ProductsController@show');
	    Route::name('admin.products.edit')->get('/{product}/edit', 'ProductsController@edit');
	    Route::name('admin.products.update')->put('/{product}', 'ProductsController@update');
	    Route::name('admin.products.destroy')->delete('/{product}', 'ProductsController@destroy');
	});

	Route::group(['prefix' => 'modules'], function () {
	    Route::name('admin.modules.index')->get('/', 'ModulesController@index');
	    Route::name('admin.modules.create')->get('/create', 'ModulesController@create');
	    Route::name('admin.modules.store')->post('/', 'ModulesController@store');
	    Route::name('admin.modules.show')->get('/{module}', 'ModulesController@show');
	    Route::name('admin.modules.edit')->get('/{module}/edit', 'ModulesController@edit');
	    Route::name('admin.modules.update')->put('/{module}', 'ModulesController@update');
	    Route::name('admin.modules.destroy')->delete('/{module}', 'ModulesController@destroy');
	});

    Route::group(['prefix' => 'users'], function () {
	    Route::name('admin.users.index')->get('/', 'UsersController@index');
	    Route::name('admin.users.create')->get('/create', 'UsersController@create');
	    Route::name('admin.users.store')->post('/', 'UsersController@store');
	    Route::name('admin.users.show')->get('/{user}', 'UsersController@show');
	    Route::name('admin.users.edit')->get('/{user}/edit', 'UsersController@edit');
	    Route::name('admin.users.update')->put('/{user}', 'UsersController@update');
	    Route::name('admin.users.destroy')->delete('/{user}', 'UsersController@destroy');
	});

	Route::group(['prefix' => 'roles'], function () {
	    Route::name('admin.roles.index')->get('/', 'RolesController@index');
	});

	Route::group(['prefix' => 'timezones'], function () {
	    Route::name('admin.timezones.index')->get('/', 'TimezonesController@index');
	});

	Route::group(['prefix' => 'permissions'], function () {
	    Route::name('admin.permissions.index')->get('/', 'PermissionsController@index');
	});

});

app/Models/Admin/User.php
<?php

namespace App\Models\Admin;

use App\Traits\ActionsGenerator;
use App\Traits\MutatorsTrait;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Illuminate\Support\Facades\Storage;
use Laratrust;
use Laratrust\Traits\LaratrustUserTrait;

class User extends Authenticatable
{
    use ActionsGenerator;
    use LaratrustUserTrait;
    use MutatorsTrait;
    use Notifiable;

    protected $slug = 'users';

    protected $appends = [
        'html_actions',
        'html_active',
        'html_avatar',
        'html_email',
        'text_role_display_name',
        'text_role_id',
        'text_timezone_label',
    ];

    protected $casts = [
        //
    ];

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    // RELATIONSHIPS

    public function timezone()
    {
        return $this->belongsTo(Timezone::class, 'timezone_id');
    }

    // ACCESSORS

    public function getHtmlActionsAttribute()
    {
        $key = $this->getKey();
        $name = $this->name;

        $actions[0] = $this->action_view(Laratrust::can("browse_{$this->slug}"), route("admin.{$this->slug}.show", $key), $key);
        $actions[1] = $this->action_edit(Laratrust::can("edit_{$this->slug}"), route("admin.{$this->slug}.edit", $key), $key);
        $actions[2] = $this->action_delete(Laratrust::can("delete_{$this->slug}"), route("admin.{$this->slug}.destroy", $key), $key, $name);

        return implode(" ", $actions);
    }

    public function getHtmlActiveAttribute()
    {
        $active = $this->getAttributeValue('active');

        $class = (isset($active) && $active) ? 'success' : 'danger';
        $title = (isset($active) && $active) ? __('generic.active') : __('generic.inactive');
        
        $html = "<span class='label label-{$class}'>{$title}</<span>";

        return $html;
    }

    public function getHtmlAvatarAttribute()
    {
        $route = $this->getAttributeValue('text_avatar');

        $html = "<img src='{$route}' class='img-circle' style='width:50px;height:50px'>";

        return $html;
    }

    public function getTextAvatarAttribute()
    {
        $avatar = $this->getAttributeValue('avatar');

        $url = (isset($avatar) && !empty($avatar)) ? $avatar : 'users/default.png';
        $path = Storage::disk('public')->url($url);

        return str_replace('\\', '/', $path);
    }

    public function getHtmlEmailAttribute()
    {
        $email = $this->getAttributeValue('email');

        $html = "<a href='mailto:{$email}'>{$email}</a>";

        return $html;
    }

    public function getTextFullnameAttribute()
    {
        $name = $this->getAttributeValue('name');
        
        $last_name = $this->getAttributeValue('last_name');

        return isset($last_name) ? "{$name} {$last_name}" : $name;
    }

    public function getTextRoleDisplayNameAttribute()
    {
        $relation = $this->getRelationValue('roles')->first();

        return isset($relation) ? $relation->display_name : null;
    }

    public function getTextRoleIdAttribute()
    {
        $relation = $this->getRelationValue('roles')->first();

        return isset($relation) ? $relation->id : null;
    }

    public function getTextTimezoneLabelAttribute()
    {
        $relation = $this->getRelationValue('timezone');

        return isset($relation) ? $relation->label : null;
    }
}

resources/views/layouts/adminlte/admin/partials/topbar/messages.blade.php
<!-- Messages: style can be found in dropdown.less-->
<li class="dropdown messages-menu">
  <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown">
    <i class="fa fa-envelope-o"></i>
    <span class="label label-success">0</span>
  </a>
  <ul class="dropdown-menu">
    <li class="header">You have 4 messages</li>
    <li>
      <!-- inner menu: contains the actual data -->
      <ul class="menu">
        <li><!-- start message -->
          <a href="javascript:void(0)">
            <div class="pull-left">
              <img src="{{ asset('adminlte/dist/img/user2-160x160.jpg') }}" class="img-circle" alt="User Image">
            </div>
            <h4>
              Support Team
              <small><i class="fa fa-clock-o"></i> 5 mins</small>
            </h4>
            <p>Why not buy a new awesome theme?</p>
          </a>
        </li>
        <!-- end message -->
        <li>
          <a href="javascript:void(0)">
            <div class="pull-left">
              <img src="{{ asset('adminlte/dist/img/user3-128x128.jpg') }}" class="img-circle" alt="User Image">
            </div>
            <h4>
              AdminLTE Design Team
              <small><i class="fa fa-clock-o"></i> 2 hours</small>
            </h4>
            <p>Why not buy a new awesome theme?</p>
          </a>
        </li>
        <li>
          <a href="javascript:void(0)">
            <div class="pull-left">
              <img src="{{ asset('adminlte/dist/img/user4-128x128.jpg') }}" class="img-circle" alt="User Image">
            </div>
            <h4>
              Developers
              <small><i class="fa fa-clock-o"></i> Today</small>
            </h4>
            <p>Why not buy a new awesome theme?</p>
          </a>
        </li>
        <li>
          <a href="javascript:void(0)">
            <div class="pull-left">
              <img src="{{ asset('adminlte/dist/img/user3-128x128.jpg') }}" class="img-circle" alt="User Image">
            </div>
            <h4>
              Sales Department
              <small><i class="fa fa-clock-o"></i> Yesterday</small>
            </h4>
            <p>Why not buy a new awesome theme?</p>
          </a>
        </li>
        <li>
          <a href="javascript:void(0)">
            <div class="pull-left">
              <img src="{{ asset('adminlte/dist/img/user4-128x128.jpg') }}" class="img-circle" alt="User Image">
            </div>
            <h4>
              Reviewers
              <small><i class="fa fa-clock-o"></i> 2 days</small>
            </h4>
            <p>Why not buy a new awesome theme?</p>
          </a>
        </li>
      </ul>
    </li>
    <li class="footer"><a href="javascript:void(0)">See All Messages</a></li>
  </ul>
</li>

resources/views/layouts/adminlte/admin/partials/topbar/notifications.blade.php
<!-- Notifications: style can be found in dropdown.less -->
<li class="dropdown notifications-menu">
  <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown">
    <i class="fa fa-bell-o"></i>
    <span class="label label-warning">0</span>
  </a>
  <ul class="dropdown-menu">
    <li class="header">You have 10 notifications</li>
    <li>
      <!-- inner menu: contains the actual data -->
      <ul class="menu">
        <li>
          <a href="javascript:void(0)">
            <i class="fa fa-users text-aqua"></i> 5 new members joined today
          </a>
        </li>
        <li>
          <a href="javascript:void(0)">
            <i class="fa fa-warning text-yellow"></i> Very long description here that may not fit into the
            page and may cause design problems
          </a>
        </li>
        <li>
          <a href="javascript:void(0)">
            <i class="fa fa-users text-red"></i> 5 new members joined
          </a>
        </li>
        <li>
          <a href="javascript:void(0)">
            <i class="fa fa-shopping-cart text-green"></i> 25 sales made
          </a>
        </li>
        <li>
          <a href="javascript:void(0)">
            <i class="fa fa-user text-red"></i> You changed your username
          </a>
        </li>
      </ul>
    </li>
    <li class="footer"><a href="javascript:void(0)">View all</a></li>
  </ul>
</li>

resources/views/layouts/adminlte/admin/partials/topbar/tasks.blade.php
<!-- Tasks: style can be found in dropdown.less -->
<li class="dropdown tasks-menu">
  <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown">
    <i class="fa fa-flag-o"></i>
    <span class="label label-danger">0</span>
  </a>
  <ul class="dropdown-menu">
    <li class="header">You have 9 tasks</li>
    <li>
      <!-- inner menu: contains the actual data -->
      <ul class="menu">
        <li><!-- Task item -->
          <a href="javascript:void(0)">
            <h3>
              Design some buttons
              <small class="pull-right">20%</small>
            </h3>
            <div class="progress xs">
              <div class="progress-bar progress-bar-aqua" style="width: 20%" role="progressbar"
                   aria-valuenow="20" aria-valuemin="0" aria-valuemax="100">
                <span class="sr-only">20% Complete</span>
              </div>
            </div>
          </a>
        </li>
        <!-- end task item -->
        <li><!-- Task item -->
          <a href="javascript:void(0)">
            <h3>
              Create a nice theme
              <small class="pull-right">40%</small>
            </h3>
            <div class="progress xs">
              <div class="progress-bar progress-bar-green" style="width: 40%" role="progressbar"
                   aria-valuenow="20" aria-valuemin="0" aria-valuemax="100">
                <span class="sr-only">40% Complete</span>
              </div>
            </div>
          </a>
        </li>
        <!-- end task item -->
        <li><!-- Task item -->
          <a href="javascript:void(0)">
            <h3>
              Some task I need to do
              <small class="pull-right">60%</small>
            </h3>
            <div class="progress xs">
              <div class="progress-bar progress-bar-red" style="width: 60%" role="progressbar"
                   aria-valuenow="20" aria-valuemin="0" aria-valuemax="100">
                <span class="sr-only">60% Complete</span>
              </div>
            </div>
          </a>
        </li>
        <!-- end task item -->
        <li><!-- Task item -->
          <a href="javascript:void(0)">
            <h3>
              Make beautiful transitions
              <small class="pull-right">80%</small>
            </h3>
            <div class="progress xs">
              <div class="progress-bar progress-bar-yellow" style="width: 80%" role="progressbar"
                   aria-valuenow="20" aria-valuemin="0" aria-valuemax="100">
                <span class="sr-only">80% Complete</span>
              </div>
            </div>
          </a>
        </li>
        <!-- end task item -->
      </ul>
    </li>
    <li class="footer">
      <a href="javascript:void(0)">View all tasks</a>
    </li>
  </ul>
</li>

resources/views/layouts/adminlte/admin/partials/topbar/user_menu.blade.php
  <!-- User Account: style can be found in dropdown.less -->
  <li class="dropdown user user-menu">
    <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown">
      <img src="{{ asset('images/user.png') }}" class="user-image" alt="User Image">
      <span class="hidden-xs">{{ Auth::user()->text_fullname }}</span>
    </a>
    <ul class="dropdown-menu">
      <!-- User image -->
      <li class="user-header">
        <img src="{{ asset('images/user.png') }}" class="img-circle" alt="User Image">

        <p>
          {{ Auth::user()->text_fullname }}
          <small>{{ Auth::user()->email }}</small>
        </p>
      </li>
      <!-- Menu Body -->
      <li class="user-body">
        <div class="row">
          <div class="col-xs-4 text-center">
            <a href="javascript:void(0)"></a>
          </div>
          <div class="col-xs-4 text-center">
            <a href="javascript:void(0)"></a>
          </div>
          <div class="col-xs-4 text-center">
            <a href="javascript:void(0)"></a>
          </div>
        </div>
        <!-- /.row -->
      </li>
      <!-- Menu Footer-->
      <li class="user-footer">
        <div class="pull-left">
          <a href="javascript:void(0)" class="btn bg-navy btn-flat">Profile</a>
        </div>
        <div class="pull-right">
          <a href="{{ route('logout') }}" class="btn bg-red btn-flat" onclick="event.preventDefault(); document.getElementById('logout-form').submit();">Sign out</a>
            <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">{{ csrf_field() }}</form>
        </div>
      </li>
    </ul>
  </li>